### ISSUE TITLE
请问这个gradle错误怎么解决？

### ISSUE THREAD

**Issue by chanjamin** [waylau/spring-security-tutorial#10]
C:\Program Files\Java\jdk1.8.0_121\jre\lib\security\cacerts (系统找不到指定的文件。)

**Comment by zjs1224522500** [comment]
@chanjamin https://stackoverflow.com/questions/23903842/unable-to-import-certificate-to-cacerts

**Comment by chanjamin** [comment]
该导入自己生成的证书还是对应maven站点的呢？

**Comment by chanjamin** [comment]
该导入自己生成的证书还是对应maven站点的呢？ @zjs1224522500

**Comment by zjs1224522500** [comment]
@chanjamin 自己的

**Comment by chanjamin** [comment]
@zjs1224522500 谢谢
