### ISSUE TITLE
https://waylau.com/principle-and-practice-of-oauth2  this url may be inaccessible 

### ISSUE THREAD

**Issue by lexburner** [waylau/spring-security-tutorial#3]

**Comment by waylau** [comment]
![001](https://user-images.githubusercontent.com/3233966/27849865-f04dfeaa-6182-11e7-9192-e8956507e659.jpg)

目测，是你那边的网络问题。当然，本身我的域名，已经 被 GFW 了，所以也不是很稳定。多刷几次，或者用翻墙 ，就没问题了。感谢您的反馈~
