### ISSUE TITLE
applictions/new 信息配置

### ISSUE THREAD

**Issue by ninuxGithub** [waylau/spring-security-tutorial#6]
https://github.com/settings/applications/new 页面的配置, homepageurl 和 authorizationcallbackurl分别是？

**Comment by waylau** [comment]
* homepageurl ： 应用的主页。
* authorizationcallbackurl ： 认证后，回调的URL

本例子的配置，见下图
![qq 20171019220305](https://user-images.githubusercontent.com/3233966/31774866-84f42a4a-b519-11e7-9ef1-b6a6151935ac.jpg)

**Comment by ninuxGithub** [comment]
authorizationcallbackurl  :这个地址我试了很多回  都是报错  url mismatch ...，填写的效果怎么和您不一样，
我看您是跳转到了https://github.com 页面进行授权确认

**Comment by waylau** [comment]
@ninuxGithub   已经上传了截图，你看下~
