### ISSUE TITLE
每个子模块不应该加上版本号吗❓，编译通不过吧

### ISSUE THREAD

**Issue by jackblack369** [waylau/spring-security-tutorial#7]
根目录的springBootVersion配置，为啥没有应用到子模板库中，比如
![image](https://user-images.githubusercontent.com/12108942/32761009-f3824804-c92b-11e7-9258-3e14d1680944.png)

**Comment by chuckie-xch** [comment]
从来没有见过这么垃圾的toturial,代码没有一个可以正确运行的

**Comment by waylau** [comment]
@jackblack369   已经解决了~
